### ISSUE TITLE
Feature request: Listen for the `storage` event to keep `localStorage` synced across multiple tabs

### ISSUE THREAD

**Issue by Greenheart** [efstajas/svelte-stored-writable#1]
Nice library! Especially the combination of using zod to parse data, and automatically initialising the store. (I've previously manually initialised the store on each page with [this implementation](https://github.com/Greenheart/idg.tools/blob/0cf1516834d51597d2978c230f495fdf55daf7fe/tools/src/lib/stores.ts#L5-L28) which works but is a worse DX).

One feature that could be a nice addition to this library is to listen for the [`storage` event on the window](https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event), and always use the latest value no matter which tab has been used. This event tells us which `localStorage` key that was changed, making it possible to only update when the relevant key has changed in another tab.

To keep the core library clean, this feature should likely be opt-in when creating the store.

**Comment by efstajas** [comment]
This is a great suggestion, will add this soon, thanks.

**Comment by efstajas** [comment]
@Greenheart This is added in v0.2.0 :)
